# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd8374fd37b1e6d0a20cc11733578e39c8589ac2572dd440d229c6351d3b05df2de48198d527c0e83d544a9399e5198b743f463205f28e9ac6316df53e8685fc

test:
  secret_key_base: 55b74298b9bca5feec6568a9f07eac1eb66bc31fbd9023758b3920bd7e59d4d3c89bc1b680f61d28ad0e266cb3717c34d532916212926c732d4b7f274b810dca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
